stages:
  - build
  - deploy

Check-on:
  image: maven:latest
  services:
    - postgres:latest
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    POSTGRES_USER: $postgres_user
    POSTGRES_PASSWORD: $postgres_password
    POSTGRES_DB: $postgres_db
    POSTGRES_HOST_AUTH_METHOD: trust
    TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  cache:
    paths:
      - .m2/repository
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install'
    - echo "$CI_JOB_STAGE was successful"
    - echo "build number $CI_PIPELINE_ID"