version: '3'

services:
  postgres:
    image: 'postgres:latest'
    hostname: postgres
    container_name: socialnet-db
    environment:
     POSTGRES_DB: socialnet
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: passWd123
    ports:
    - "5455:5432"
    restart: unless-stopped

  frontend:
    image: 'kohgutepdev/front:latest'
    container_name: frontend
    ports:
      - "8098:80"
    restart: unless-stopped

  core:
    image: 'kohgutepdev/team29socialnet-core:latest'
    container_name: core-service
    ports:
      - "8086:8086"

  db:
    image: 'kohgutepdev/team29socialnet-db:latest'
    container_name: db-service
    ports:
      - "8081:8081"