server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://socialnet-db:5432/socialnet
    username: admin
    password: passWd123

  liquibase:
    change-log: classpath:liquibase/changelog.xml
    enabled: true
